### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by hexxone** [llSourcell/Watch-Me-Build-a-Trading-Bot#3]
**Note: this is the technical bug tracker, please use other platforms for getting support and starting a (non technical) discussion. See the [getting help page](https://gekko.wizb.it/docs/introduction/getting-help.html) for details.**

**I'm submitting a ...**
[ x] bug report
[ ] question about the decisions made in the repository

**Action taken** 
Followed the instuctions to set up the bot from the Readme.md and wanted to start importing Data

**Expected result** 
I could select an exchange and Currency and Import the data 

**Actual result** 
On http://localhost:3000/#/data/importer The list of Exchanges to import from is empty

**Other information** 
I thought maybe I had to add an API Key first, but in the Config tab there is no field to do so.

**Comment by vinayphadnis** [comment]
This is happening because you have not installed the broker dependencies. Install the broker dependencies by typing
```sh
cd exchange  
npm install --only=production  
cd ..  
```
I have submitted a pull request #2 to add this in the installation instructions in ```README.md```

**Comment by bhouse044** [comment]
@vinayphadnis Thank you! I was having the same issue and this solution worked!
